#ifndef DEVICEMNGLIB_GLOBAL
#define DEVICEMNGLIB_GLOBAL

#include <QtCore/qglobal.h>

#if defined(DEVICEMNGLIB_LIBRARY)
#define DEVICEMNGLIB_LIBRARYSHARED_EXPORT Q_DECL_EXPORT
#else
#define DEVICEMNGLIB_LIBRARYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DEVICEMNGLIB_GLOBAL
